### ISSUE TITLE
Regarding example.py

### ISSUE THREAD

**Issue by Astro-Falcon** [Goobley/Lightspinner#1]
You mention about running the synthesis in the example.py file but there is no such file in the directory, am I missing something?

**Comment by Goobley** [comment]
Oh, apologies, this must have been a typo in my part. The file `test.py` is an example driver script. I should update the readme.

**Comment by Astro-Falcon** [comment]
Ohh, no worries.
Thanks for the clarification.

**Comment by Astro-Falcon** [comment]
There is just one more doubt that I have is that,
In the fal.py file, what are the six elements in the nh array?
Which population do they correspond to?
Sorry, but I am new to radiative transfer codes.

**Comment by Goobley** [comment]
This is a quirk of the way atmospheres are used in the RH and MULTI codes. The 6 levels per depth correspond to the 6 energy levels of the "typical" 6 level hydrogen atom that is commonly used in NLTE RT. That said, this isn't  used in Lightspinner. Instead, these populations are summed over to get the `nHTot` variable which is used as the reference to scale the other atomic densities.

**Comment by Astro-Falcon** [comment]
Just one last question, how can I get the electron and hydrogen population for defining my own environment?

**Comment by Goobley** [comment]
Apologies, did you figure this out? It should be a matter of just constructing a new `Atmosphere` object.

**Comment by Astro-Falcon** [comment]
I was able to take inspiration from the methods that MURaM code uses to output different physical quantities which is mostly interpolation using the OPAL or Uppsala eos tables.
